version: '3'

services:
  postgres:
    image: postgres:10.5
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-scripts/01_ddl_initial_script.sql:/docker-entrypoint-initdb.d/01_ddl_initial_script.sql
      - ./init-scripts/02_dml_initial_script.sql:/docker-entrypoint-initdb.d/02_dml_initial_script.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  desafio-simples-dental:
    image: desafio-simples-dental:1.0
    container_name: desafio-simples-dental
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
